"""Initial tables

Revision ID: 347c30465dba
Revises: 
Create Date: 2025-12-19 15:16:29.372297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '347c30465dba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('balance_usdc', sa.Float(), nullable=False),
    sa.Column('balance_echelon', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('archetype', sa.Enum('SHARK', 'SPY', 'DIPLOMAT', 'SABOTEUR', 'WHALE', 'DEGEN', name='agentarchetype'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sanity', sa.Integer(), nullable=False),
    sa.Column('max_sanity', sa.Integer(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('death_cause', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('wallet_address', sa.String(length=100), nullable=False),
    sa.Column('total_pnl_usd', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('genome', sa.JSON(), nullable=False),
    sa.Column('parent_agent_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_alive', 'agents', ['is_alive'], unique=False)
    op.create_index('ix_agents_archetype', 'agents', ['archetype'], unique=False)
    op.create_index('ix_agents_owner', 'agents', ['owner_id'], unique=False)
    op.create_table('timelines',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('surface_tension', sa.Float(), nullable=False),
    sa.Column('price_yes', sa.Float(), nullable=False),
    sa.Column('price_no', sa.Float(), nullable=False),
    sa.Column('osint_alignment', sa.Float(), nullable=False),
    sa.Column('logic_gap', sa.Float(), nullable=False),
    sa.Column('gravity_score', sa.Float(), nullable=False),
    sa.Column('gravity_factors', sa.JSON(), nullable=False),
    sa.Column('total_volume_usd', sa.Float(), nullable=False),
    sa.Column('liquidity_depth_usd', sa.Float(), nullable=False),
    sa.Column('active_agent_count', sa.Integer(), nullable=False),
    sa.Column('decay_rate_per_hour', sa.Float(), nullable=False),
    sa.Column('decay_multiplier', sa.Float(), nullable=False),
    sa.Column('founder_id', sa.String(length=50), nullable=True),
    sa.Column('founder_yield_rate', sa.Float(), nullable=False),
    sa.Column('parent_timeline_id', sa.String(length=50), nullable=True),
    sa.Column('connected_timeline_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('has_active_paradox', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timelines_active', 'timelines', ['is_active'], unique=False)
    op.create_index('ix_timelines_gravity', 'timelines', ['gravity_score'], unique=False)
    op.create_index('ix_timelines_stability', 'timelines', ['stability'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_index('ix_watchlist_user_item', 'watchlist_items', ['user_id', 'item_type', 'item_id'], unique=True)
    op.create_table('paradoxes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('timeline_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXTRACTING', 'DETONATED', 'RESOLVED', name='paradoxstatus'), nullable=False),
    sa.Column('severity_class', sa.Enum('CLASS_1_CRITICAL', 'CLASS_2_SEVERE', 'CLASS_3_MODERATE', 'CLASS_4_MINOR', name='severityclass'), nullable=False),
    sa.Column('logic_gap', sa.Float(), nullable=False),
    sa.Column('spawned_at', sa.DateTime(), nullable=False),
    sa.Column('detonation_time', sa.DateTime(), nullable=False),
    sa.Column('decay_multiplier', sa.Float(), nullable=False),
    sa.Column('extraction_cost_usdc', sa.Float(), nullable=False),
    sa.Column('extraction_cost_echelon', sa.Integer(), nullable=False),
    sa.Column('carrier_sanity_cost', sa.Integer(), nullable=False),
    sa.Column('carrier_agent_id', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['carrier_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paradoxes_status', 'paradoxes', ['status'], unique=False)
    op.create_index('ix_paradoxes_timeline', 'paradoxes', ['timeline_id'], unique=False)
    op.create_index(op.f('ix_paradoxes_timeline_id'), 'paradoxes', ['timeline_id'], unique=False)
    op.create_table('private_forks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('base_timeline_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('simulation_result', sa.Text(), nullable=True),
    sa.Column('can_publish', sa.Boolean(), nullable=False),
    sa.Column('published_timeline_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_timeline_id'], ['timelines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_forks_user_id'), 'private_forks', ['user_id'], unique=False)
    op.create_table('user_positions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('timeline_id', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('shards_held', sa.Integer(), nullable=False),
    sa.Column('average_entry_price', sa.Float(), nullable=False),
    sa.Column('is_founder', sa.Boolean(), nullable=False),
    sa.Column('founder_yield_earned_usd', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_positions_timeline_id'), 'user_positions', ['timeline_id'], unique=False)
    op.create_index(op.f('ix_user_positions_user_id'), 'user_positions', ['user_id'], unique=False)
    op.create_index('ix_user_positions_user_timeline', 'user_positions', ['user_id', 'timeline_id'], unique=True)
    op.create_table('wing_flaps',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timeline_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('flap_type', sa.Enum('TRADE', 'SHIELD', 'SABOTAGE', 'RIPPLE', 'PARADOX', 'FOUNDER_YIELD', name='wingflaptype'), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('stability_delta', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('volume_usd', sa.Float(), nullable=False),
    sa.Column('timeline_stability', sa.Float(), nullable=False),
    sa.Column('timeline_price', sa.Float(), nullable=False),
    sa.Column('spawned_ripple', sa.Boolean(), nullable=False),
    sa.Column('ripple_timeline_id', sa.String(length=50), nullable=True),
    sa.Column('founder_yield_earned', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wing_flaps_agent_id'), 'wing_flaps', ['agent_id'], unique=False)
    op.create_index('ix_wing_flaps_agent_time', 'wing_flaps', ['agent_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_wing_flaps_timeline_id'), 'wing_flaps', ['timeline_id'], unique=False)
    op.create_index('ix_wing_flaps_timeline_time', 'wing_flaps', ['timeline_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_wing_flaps_timestamp'), 'wing_flaps', ['timestamp'], unique=False)
    op.create_index('ix_wing_flaps_type', 'wing_flaps', ['flap_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wing_flaps_type', table_name='wing_flaps')
    op.drop_index(op.f('ix_wing_flaps_timestamp'), table_name='wing_flaps')
    op.drop_index('ix_wing_flaps_timeline_time', table_name='wing_flaps')
    op.drop_index(op.f('ix_wing_flaps_timeline_id'), table_name='wing_flaps')
    op.drop_index('ix_wing_flaps_agent_time', table_name='wing_flaps')
    op.drop_index(op.f('ix_wing_flaps_agent_id'), table_name='wing_flaps')
    op.drop_table('wing_flaps')
    op.drop_index('ix_user_positions_user_timeline', table_name='user_positions')
    op.drop_index(op.f('ix_user_positions_user_id'), table_name='user_positions')
    op.drop_index(op.f('ix_user_positions_timeline_id'), table_name='user_positions')
    op.drop_table('user_positions')
    op.drop_index(op.f('ix_private_forks_user_id'), table_name='private_forks')
    op.drop_table('private_forks')
    op.drop_index(op.f('ix_paradoxes_timeline_id'), table_name='paradoxes')
    op.drop_index('ix_paradoxes_timeline', table_name='paradoxes')
    op.drop_index('ix_paradoxes_status', table_name='paradoxes')
    op.drop_table('paradoxes')
    op.drop_index('ix_watchlist_user_item', table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('ix_timelines_stability', table_name='timelines')
    op.drop_index('ix_timelines_gravity', table_name='timelines')
    op.drop_index('ix_timelines_active', table_name='timelines')
    op.drop_table('timelines')
    op.drop_index('ix_agents_owner', table_name='agents')
    op.drop_index('ix_agents_archetype', table_name='agents')
    op.drop_index('ix_agents_alive', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
